### ISSUE TITLE
Login window hangs on white screen, never logs in

### ISSUE THREAD

**Issue by w-biggs** [0xroko/obsidian-arena-plugin#1]
Thanks for building this, this seems really nice! Unfortunately though I can't get it to work, when I try to log in, after authorizing, it just sits like this:

<img width="655" alt="image" src="https://github.com/0xroko/obsidian-arena-plugin/assets/3406010/ed198649-27fd-4eaa-8226-6eb3e3481545">

**Comment by w-biggs** [comment]
It also seems to be doing some weird actions like attempting to delete certain files, creating new folders, etc. when I try to log in. No idea why

**Comment by 0xroko** [comment]
Hi, 

I'm able to replicate both "weird actions" when opening login window and login issues. Looks like Obsidian is having an issue with opening external browser window... Will look in to it tomorrow.

**Comment by 0xroko** [comment]
Just released `1.0.1.` which includes few small fixes. Can you please update both obsidian and the plugin to the latest version and try to log in again. 

If the issue still persists, try to log in in with open devtools (open them with `cmd + option + t`) and see if any errors are logged to the console.

**Comment by w-biggs** [comment]
I got it to log in but it did still do a couple weird things on login (it opened the command palette, the file select palette, and created an empty folder in my vault called `are.na`.)

However, it's not able to add blocks to a canvas -- it says "error saving block". In the devtools I get this error:

```
Error saving block TypeError: Cannot read properties of undefined (reading 'block')
    at ArenaPlugin.saveBlock (plugin:arena:1212:44)
    at InsertBlockModal.eval [as onSubmit] (plugin:arena:1326:37)
    at form.onsubmit (plugin:arena:1413:14)```

**Comment by 0xroko** [comment]
Sorry for a long awaited answer. Closing this as it should be fixed, since plugin no longer requires login.
